### PR TITLE
feat(setup): initial pre-commit config

### LINKED ISSUE #27: Create coding guidelines
## Task
Create and agree on coding guidelines and additional tools (linting, auto-formatting, git pre-commit) which every developers agrees on and uses it.

### PR DESCRIPTION
**Pull request by vringar**
Closes #27

### CODE REVIEW

**Comment by vringar** [comment]
@jandegen I used the issue number in the branch name and it didn't trigger the linking.
Or should the name be `feat/27-coding-guidelines`?

**Comment by jandegen** [comment]
Not sure about prs but the issue is linked with the branch 
If you put „#27“ in the title it could also link the pr

**Comment by vringar** [comment]
It's linked now after I put the reference in the PR description

**Comment by vringar** [comment]
If this PR is accepted we will have [these types of commits](https://github.com/conventional-changelog/commitlint/blob/79897098cc356387555f42c63e22c2810e5b61f6/%40commitlint/config-conventional/index.js#L18-L34)
GitHub now has a Beta feature called branch rules, which we could use to restrict the branch names as well.

I think it makes sense to align the commit types and branch types, but I'll also bring this up on Monday.

**Review by freefreeP — APPROVED** [review]

**Review by muhdfahadali — APPROVED** [review]

**Pull request merged**
