### PR TITLE
docs(architecture): initial architecture draft

### LINKED ISSUE #8: Create software architecture description
## Task
Prepare a description of the planned software architecture; include
- [ ] An overview diagram of runtime components (one page)
- [ ] An overview diagram of code components (one page)
- [ ] A summary of the underlying technology stack (one page)
- [ ] A textual explanation of the diagrams and choices (one page)

### PR DESCRIPTION
**Pull request by vringar**
Closes #8

### CODE REVIEW

**Comment by vringar** [comment]
The document is best viewed [here](https://github.com/amosproj/amos2023ss04-kubernetes-inventory-taker/blob/software-architecture/Documentation/Software-Architecture.md).

**Review by freefreeP — COMMENTED** [review]
Is it mandatory to use k8s. Can we have a discussion if we should use k3s for simplicity?

**Comment by vringar** [comment]
I thought k3s was a way of deploying/a version of K8s?
The kubernetes API spec is still implemented by k3s right?

**Comment by freefreeP** [comment]
Yes both, was just asking if that was another weird hard requirement. But yeah you are right we should be able to deploy as we like, they should not care and they can deploy as they like either k3s client or k8s client since they are api compatible.

**Review by muhdfahadali — APPROVED** [review]

**Review by freefreeP — APPROVED** [review]

**Review by njochens — APPROVED** [review]

**Pull request merged**
